- name: Creates directory
  become: true
  file:
    path: ~/backend
    state: directory

- name: Install dependencies
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes    

- name: Extract backend files to EC2
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: Executing node
  become: true
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start