- name: Creates directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract backend files to EC2
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: Executing node
  become: true
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start