---
- name: Create directory
  shell: mkdir ~/backend

- name: Extract backend files to EC2
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: Executing node
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start